language: node_js
node_js:
  - "7"
  - "6"
branches:
  only:
  - master
deploy:
  - provider: npm
    skip_cleanup: true
    email: andrei.moldoveanu@gmail.com
    api_key:
      secure: "4AEpH+a7UBTzDJZr/0khq5pvhFTmEzEw9LRaxAmT6Js+O7wYS/aBNMcF7L2ahJUFdnnRtbt4gL8den2YsEjKEuDFIwO4s4ahSWulFu0IECRcyxsSBCcPKeG537+pFCuzB2lxMJ81zc8KcbGmMPfY/X46DEgHMvu2KEpJM0EmZdLplesPcsHkN7tpOFjpTHO6uwjDS/Ok4tr1M3ZEz/z8xA6Lvg1el8nU9tlEZe1vRTGCylyFe8cbwuOKq23NRjJtJkec/tnQ+eneFyO/SRMraGZY/IGf4NtlrzoQkDGIhINZxZFk5yB6A1GaF8WEzxBWJqkfEFU2bUPozgMW3igpAm2a+/6XQG0MGqS0aKM+dPhY+nWqpBqDUkk/QH/TVupR1ykMDvT6ZcNt01LfvO2LgylrZCzXO00+eBQO9pgDh06igat1If17cmnipO+XRWUwMv5i+sGy7S4kBIxXmeeDZYKMeKVMKjFOTHx3P1gVLMEQ+EN04kJZ9RY2PcyUwIMJBp0/5DgF58Z4CuMUieyaG1y6z4F9fVdWIX27iuzJcJFMzUlO1fFaMSMbc5rERhXZFiqiRkNky7jawfMgkVXnKK1jTmuHp583MnclxjYSbckMiqSJYoCatX26yX25k5hRQQ2lxXxWExTdoVZetG53vbZ6hGwyXwUtdJL4XOoPuY4="
    on:
      tags: true
