#project information
site_name: Rebilly JS SDK
site_description: Official Rebilly JS SDK Documentation

#theme
theme_dir: 'mkdocs-material/material'
extra_css:
  - 'styles/extra.css'

#repo information
repo_name: 'Rebilly JS SDK'
repo_url: 'https://github.com/Rebilly/rebilly-js-sdk'

# Copyright
copyright: 'Copyright &copy; 2017 Rebilly Inc.'

#extensions
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc(permalink=true)
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.mark

#page tree
pages:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Reference:
    - RebillyAPI: reference/rebilly-api.md
    - RebillyExperimentalAPI: reference/rebilly-experimental-api.md
    - RebillyErrors: reference/rebilly-errors.md
    - Resources:
      - Accounts: reference/resources/accounts.md
    - Experimental:
      - Accounts: reference/resources/experimental/accounts.md
    - Response Types:
      - Member: reference/types/member.md
      - Collection: reference/types/collection.md
      - File: reference/types/file.md
  - License: license.md

