#project information
site_name: Rebilly JS SDK
site_description: Official Rebilly JS SDK Documentation
site_favicon: 'images/favicon.ico'

#theme
theme: 'material'
extra_css:
  - 'styles/extra.css'

extra:
  palette:
    primary: 'indigo'
    accent: 'deep purple'

#repo information
repo_name: 'Rebilly JS SDK'
repo_url: 'https://github.com/Rebilly/rebilly-js-sdk'

# Copyright
copyright: 'Copyright &copy; 2017 Rebilly Inc.'

#extensions
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc(permalink=true)
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.snippets(base_path=docs)
  #  - pymdownx.smartsymbols

#page tree
pages:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Reference:
    - RebillyAPI: reference/rebilly-api.md
    - RebillyExperimentalAPI: reference/rebilly-experimental-api.md
    - RebillyErrors: reference/rebilly-errors.md
    - Resources:
      - Accounts: reference/resources/account.md
      - API Keys: reference/resources/api-keys.md
      - Bank Accounts: reference/resources/bank-accounts.md
      - Blacklists: reference/resources/blacklists.md
      - Checkout Pages: reference/resources/checkout-pages.md
      - Contacts: reference/resources/contacts.md
      - Coupons: reference/resources/coupons.md
      - Credential Hashes: reference/resources/credential-hashes.md
      - Custom Events: reference/resources/custom-events.md
      - Custom Fields: reference/resources/custom-fields.md
      - Customers: reference/resources/customers.md
      - Customer Authentication: reference/resources/customer-authentication.md
      - Disputes: reference/resources/disputes.md
      - Events: reference/resources/events.md
      - Files: reference/resources/files.md
    - Experimental:
      - Accounts: reference/resources/experimental/accounts.md
    - Response Types:
      - Member: reference/types/member.md
      - Collection: reference/types/collection.md
      - File: reference/types/file.md
  - Guides:
    - Criteria: guides/criteria.md
    - Filters: guides/filters.md
  - License: license.md

